using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("DeltaEngine")]
[assembly: AssemblyDescription("Delta Engine Core library for datatypes, entities, extensions and base classes used in all other projects")]
[assembly: AssemblyCompany("Delta Engine")]
[assembly: AssemblyCopyright("Copyright � Delta Engine 2013")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("32d97bc4-ae8c-4ec8-9381-952c45b82974")]
[assembly: AssemblyVersion("0.9.9.4")]
[assembly: AssemblyFileVersion("0.9.9.4")]
[assembly: InternalsVisibleTo("DeltaEngine.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Mocks")]
[assembly: InternalsVisibleTo("DeltaEngine.Content.Online.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Content.Xml.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Content.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Rendering2D")]
[assembly: InternalsVisibleTo("DeltaEngine.Rendering3D")]
[assembly: InternalsVisibleTo("DeltaEngine.Networking")]
[assembly: InternalsVisibleTo("DeltaEngine.Networking.Mocks")]
[assembly: InternalsVisibleTo("DeltaEngine.Networking.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Platforms")]
[assembly: InternalsVisibleTo("DeltaEngine.Platforms.Mocks")]
[assembly: InternalsVisibleTo("DeltaEngine.Platforms.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia.SoundDevice")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia.GLFW2")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia.GLFW3")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia.OpenTK")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia.OpenTKES")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia.SharpDX")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia.SlimDX")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia.Xna")]
[assembly: InternalsVisibleTo("DeltaEngine.Multimedia.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Input")]
[assembly: InternalsVisibleTo("DeltaEngine.Input.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Rendering2D.Sprites.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Rendering2D.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Scenes.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Tests")]
[assembly: InternalsVisibleTo("DeltaEngine.Graphics.OpenTK20")]
[assembly: InternalsVisibleTo("DeltaEngine.Graphics.OpenTK")]
[assembly: InternalsVisibleTo("DeltaEngine.Graphics.GLFW3")]